spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/myapp
      authentication-database: admin
      auto-index-creation: true
server:
  port: 8080
  servlet:
    context-path: /
logging:
  level:
    org.springframework.web: DEBUG
    ma.yc.PigeonSkyRace: DEBUG