name: CI

on:
  pull_request:
    branches:
      - main


jobs:
  build-deploy:
    name : build and deploy pigeon sky race app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      - name: Build Docker Image
        run: |
          docker build -t yourusername/yourimage:latest .  # Replace with your details

      - name: Push Docker Image
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push yourusername/yourimage:latest  # Replace with your details
